---
- name: Configure web server
  hosts: web
  become: yes

  tasks:

    - name: Stop Apache
      systemd:
        name: httpd
        state: stopped
        enabled: no

    - name: Install Nginx
      dnf:
        name: nginx
        state: present

    - name: Start Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes