---
- name: Configure web server
  hosts: web
  become: yes

- name: Stop Apache
  systemd:
    name: httpd
    state: stopped
    enabled: no

  tasks:
    - name: Install Nginx
      dnf:
        name: nginx
        state: present

    - name: Start Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes